
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1']

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: set cores number
        run: echo "JULIA_NUM_THREADS=$(getconf _NPROCESSORS_ONLN)" >> $GITHUB_ENV
      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 26f1160aa330772a6c91c59bb5de7a4c
          filename: burlp_train_solves.json
          label: Train
          message: ${{ env.TRAIN_SOLVES }}
          color: green
